name: RP2xxx build

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        board:
          - "adafruit_feather_rp2040"
          - "adafruit_itsybitsy_rp2040"
          - "adafruit_qtpy_rp2040"
          - "pico"
          - "pimoroni_keybow2040"
          - "pimoroni_picosystem"
          - "pimoroni_tiny2040"
          - "sparkfun_micromod"
          - "sparkfun_promicro"
          - "sparkfun_thingplus"
          - "vgaboard"

    steps:
    - name: checkout RF24 lib
      uses: actions/checkout@v2

    - name: Install toolchain
      run: sudo apt update && sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: Clone pico-sdk
      uses: actions/checkout@v2
      with:
        repository: raspberrypi/pico-sdk
        ref: 1.1.1
        path: pico-sdk
        clean: false
        submodules: true

    - name: Checkout pico-sdk submodules
      working-directory: ${{ github.workspace }}/pico-sdk
      run: git submodule update --init

    - name: Create Build Environment
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure CMake
      working-directory: ${{ github.workspace }}/build
      env:
        PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{ github.workspace }}/build
      # Execute the build. You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE -DPICO_BOARD=${{ matrix.board }}

    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: examples_pico_${{ matrix.board }}
        path: ${{ github.workspace }}/build/*.uf2
